import { NextRequest, NextResponse } from 'next/server';
import { readFile, stat } from 'fs/promises';
import { join } from 'path';

// Serves PNGs generated by src/services/tools/design.ts.
// Files live at project_root/generated/<uuid>.png and are written by the
// worker after a successful gstack design binary run.
//
// Security:
//   - filename is restricted to [uuid]. ext = png. No '..' allowed.
//   - 404 for anything not matching the expected shape.
//   - Not auth-gated for MVP — generated filenames are unguessable UUIDs
//     so the URL itself is the capability. If we later want per-user
//     scoping we can store ownership in a DB row and check it here.
//
// Runtime: Node (needs fs). Not Edge.

export const runtime = 'nodejs';

const GENERATED_DIR = join(process.cwd(), 'generated');
// Only accept UUIDs + .png extension. Rejects path traversal, weird chars, etc.
const FILENAME_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.png$/;

export async function GET(
  _req: NextRequest,
  { params }: { params: { filename: string } },
) {
  const { filename } = params;

  if (!filename || !FILENAME_REGEX.test(filename)) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  const filepath = join(GENERATED_DIR, filename);

  try {
    const st = await stat(filepath);
    if (!st.isFile()) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 });
    }

    const buf = await readFile(filepath);
    return new NextResponse(new Uint8Array(buf), {
      status: 200,
      headers: {
        'Content-Type': 'image/png',
        'Content-Length': String(st.size),
        // Cache aggressively — these files are immutable (content-addressed by UUID)
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }
}
